name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.25.2
      - uses: dagger/dagger-for-github@v8.2.0
      - name: Run go test
        working-directory: go
        run: go test -v ./integration

  typescript-bun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.0
      - uses: dagger/dagger-for-github@v8.2.0
      - run: dagger develop
        working-directory: typescript-bun/integration
      - name: Run bun test
        working-directory: typescript-bun
        run: |
          bun install
          bun test